### PR TITLE
Fix incorrect licence in the README

### PR DESCRIPTION
**Pull request by alpendop**
Should reflect the licence change #60

### CODE REVIEW

**Comment by gavinhenderson** [comment]
@alpendop Thank you for your contribution! 🎉🎉🎉

Can I ask that you change the name of the licence file back to its original spelling?

When writing documentation I typically try and use the British spelling of Licence. However, for the LICENSE file I use the American spelling as that is what I imagine most automated licence detection tooling would most likely detect. [The github docs also use the American spelling for the file name.](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository).

**Comment by gavinhenderson** [comment]
Thanks again @alpendop. I've merged the change now :) 

If you don't mind me asking how did you find the project? Let me know if you are looking to contribute further.

**Comment by alpendop** [comment]
> Thanks again @alpendop. I've merged the change now :)
> 
> If you don't mind me asking how did you find the project? Let me know if you are looking to contribute further.

Was lurking on Reddit to find some projects to contribute relating to JavaScript and found a comment in a thread pointing to this project. I think it was the actual organisation that posted the comment that was looking for contributors.

I was going to try to contribute more even if I don't know much about the goals of the project.

**Comment by gavinhenderson** [comment]
Thanks! I think that was @willwade who posted on Reddit. There is plenty ways you can contribute to this project if you feel like you want to. Feel free to comment on an issue and I can give you some pointers if you are looking to pick anything up!

**Pull request merged**
