### PR TITLE
Run as admin by default

### PR DESCRIPTION
**Pull request by gavinhenderson**
Todo: 
- [x] Switch to logger rather than console log

### CODE REVIEW

**Comment by gavinhenderson** [comment]
So here is where I am up to. I have the code to write to the regedit to run as admin. It works when I run it as a node script but I can't quite get it to work within EyeCommander yet.

The problem is packaging the regedit package I am using: https://github.com/ironSource/node-regedit

There is a specific note in the readme about using it with electron. However it assumes you are using electron-builder but we are using electron-packager. 😠 I'll figure it out, its just a HUGE pain

Leaving it for now, hopefully fresh eyes on monday will help me solve it

CC @willwade

**Comment by willwade** [comment]
Just incase anyone stumbles across this - Remind me why we are using electron-packager over builder?

**Comment by gavinhenderson** [comment]
@willwade Good question. 

We actually use [`electron-forge`](https://www.electronforge.io/) which is a tool for creating, publishing, and installing Electron applications. Under the hood `electron-forge` uses `electron-packager`, which we can't change.

We use `electron-forge` because it does literally everything out of the box for us. We can stop using `electron-forge` and then switch to `electron-builder` but that would require us to take on a lot of extra tooling.

I am almost certain there is a solution to solve this whilst continuing to use `electron-forge`.

**Comment by gavinhenderson** [comment]
@willwade Can you review this when you get a sec? Mainly just to check it makes sense. There is only really two new files which are worth looking at:

* https://github.com/AceCentre/EyeCommander/blob/run-as-admin/src/backend/is-admin.js
* https://github.com/AceCentre/EyeCommander/blob/run-as-admin/src/backend/squirrel-events.js

**Pull request merged**
